### ISSUE TITLE
Address change

### ISSUE THREAD

**Issue by dhanujupiter** [StartedUp/CocoNet#63]
Kindly change the address to the chennai address.
![image](https://cloud.githubusercontent.com/assets/26476938/24268889/5aeee41c-1035-11e7-93de-e080365c0590.png)

**Comment by dhanujupiter** [comment]
change the address to

4th mainroad
Rajiv Gandhi 2nd street
Perumbakkam
Chennai-600100

**Comment by balajisundaramm** [comment]
It is fixed
