### ISSUE TITLE
Kindly change product quantity selection

### ISSUE THREAD

**Issue by dhanujupiter** [StartedUp/CocoNet#78]
![image](https://user-images.githubusercontent.com/26476938/39837814-22937178-53f5-11e8-8874-30dde52ad002.png)

Per day should be changed,
Quantity is enough.
Have a doubt about how we are going to accomplish the units ( quantity can either be grams or Kgs ). But 500 gram is the minimum.
We can even provide a box below the quantity box to select the units (either gms or kgs).
Instead of “Subscribe” button, there should be “Check out or buy” button.

**Comment by balajisundaramm** [comment]
Issue is fixed.
