### ISSUE TITLE
Kindly change the subscription summary

### ISSUE THREAD

**Issue by dhanujupiter** [StartedUp/CocoNet#79]
![image](https://user-images.githubusercontent.com/26476938/39837906-5ff9a258-53f5-11e8-8298-95356ec952e3.png)
![image](https://user-images.githubusercontent.com/26476938/39837914-679d61fc-53f5-11e8-99d8-77283c748681.png)

This subscription is no longer needed, as it is not going to be on subscription basis.

This active subscriptions button is also not needed. Kindly change this into “order summary or order history”

**Comment by balajisundaramm** [comment]
Issue is fixed and the latest branch is Design_Renovating
